language: objective-c
osx_image: xcode8
xcode_sdk: iphonesimulator10.0
cache:
  directories:
    - node_modules
before_install:
  - brew update
  - brew reinstall xctool
  - brew reinstall watchman
  - yarn install
script:
  - yarn test